[chain]
name = "Atom One"
id = "atomone-1"
type = "cosmos"
registry = "atomone"
explorer_url = "https://thespectra.io/atomone"
slip44 = 118
bech32_prefix = "atone"
keplr_json = "atomone.json"

# RPC endpoints
[[chain.rpcs]]
url = "https://atomone-rpc.cogwheel.zone"
provider = "Cogwheel ⚙️"

[[chain.rpcs]]
url = "https://atomone-mainnet-rpc.itrocket.net"
provider = "ITRocket"

[[chain.rpcs]]
url = "https://rpc-atomone.ecostake.com"
provider = "Ecostake"

[[chain.rpcs]]
url = "https://rpc.atomone.citizenweb3.com"
provider = "CitizenWeb3"

# REST endpoints
[[chain.rest]]
url = "https://atomone-api.cogwheel.zone"
provider = "Cogwheel ⚙️"

[[chain.rest]]
url = "https://atomone-mainnet-api.itrocket.net"
provider = "ITRocket"

[[chain.rest]]
url = "https://rest-atomone.ecostake.com"
provider = "Ecostake"

[[chain.rest]]
url = "https://api.atomone.citizenweb3.com"
provider = "CitizenWeb3"

[[token]]
denom = "uatone"
name = "Atone"
symbol = "ATONE"
exponent = 6
icon = "https://raw.githubusercontent.com/Cogwheel-Validator/spectra-ibc-hub/main/images/atomone/atone.png"
allowed_destinations = ["osmosis-1"]

[[token]]
denom = "uphoton"
name = "Photon"
symbol = "PHOTON"
exponent = 6
icon = "https://raw.githubusercontent.com/Cogwheel-Validator/spectra-ibc-hub/main/images/atomone/photon.png"
allowed_destinations = ["osmosis-1"]
