[chain]
name = "Cosmos Hub"
id = "cosmoshub-4"
type = "cosmos"
registry = "cosmoshub"
explorer_url = "https://mintscan.io/cosmoshub"
slip44 = 118
bech32_prefix = "cosmos"
keplr_json = "cosmoshub.json"

# RPC endpoints
[[chain.rpcs]]
url = "https://rpc.cosmoshub-4.citizenweb3.com/"
provider = "CitizenWeb3"

[[chain.rpcs]]
url = "https://cosmos-rpc.polkachu.com/"
provider = "Polkachu"

[[chain.rpcs]]
url = "https://rpc-cosmoshub.ecostake.com"
provider = "Ecostake"

# REST endpoints
[[chain.rest]]
url = "https://api.cosmoshub-4.citizenweb3.com/"
provider = "CitizenWeb3"

[[chain.rest]]
url = "https://cosmos-api.polkachu.com/"
provider = "Polkachu"

[[chain.rest]]
url = "https://rest-cosmoshub.ecostake.com"
provider = "Ecostake"

[[token]]
denom = "uatom"
name = "Atom"
symbol = "ATOM"
exponent = 6
icon = "https://raw.githubusercontent.com/Cogwheel-Validator/spectra-ibc-hub/main/images/cosmoshub/atom.png"
allowed_destinations = ["osmosis-1", "stargaze-1"]