[chain]
name = "Juno Network"
id = "juno-1"
type = "cosmos"
registry = "juno"
explorer_url = "https://explorer.cogwheel.zone/juno"
slip44 = 118
bech32_prefix = "juno"
keplr_json = "juno.json"

# Packet Forward Middleware support
has_pfm = true

# RPC endpoints
[[chain.rpcs]]
url = "https://juno-rpc.cogwheel.zone"
provider = "Cogwheel ⚙️"

[[chain.rpcs]]
url = "https://juno-rpc.polkachu.com"
provider = "Polkachu"

[[chain.rpcs]]
url = "https://rpc.lavenderfive.com:443/juno"
provider = "LavenderFive"

# REST endpoints
[[chain.rest]]
url = "https://juno-api.cogwheel.zone"
provider = "Cogwheel ⚙️"

[[chain.rest]]
url = "https://juno-api.cogwheel.zone"
provider = "Polkachu"

[[chain.rest]]
url = "https://rest.lavenderfive.com:443/juno"
provider = "LavenderFive"

[[token]]
denom = "ujuno"
name = "Juno"
symbol = "JUNO"
exponent = 6
icon = "https://raw.githubusercontent.com/Cogwheel-Validator/spectra-ibc-hub/main/images/juno/juno.png"
coingecko_id = "juno-network"
allowed_destinations = ["osmosis-1", "stargaze-1"]

[[token]]
denom = "cw20:juno168ctmpyppk90d34p3jjy658zf5a5l3w8wk35wht6ccqj4mr0yv8s4j5awr"
name = "Neta"
symbol = "NETA"
exponent = 6
icon = "https://raw.githubusercontent.com/Cogwheel-Validator/spectra-ibc-hub/main/images/juno/neta.png"
coingecko_id = "neta"
allowed_destinations = ["osmosis-1"]