[chain]
name = "Noble"
id = "noble-1"
type = "cosmos"
registry = "noble"
explorer_url = "https://mintscan.io/noble"
slip44 = 118
bech32_prefix = "noble"
keplr_json = "noble.json"

# RPC endpoints
[[chain.rpcs]]
url = "https://noble-rpc.polkachu.com"
provider = "Polkachu"

[[chain.rpcs]]
url = "https://noble-rpc.owallet.io"
provider = "Owallet"

[[chain.rpcs]]
url = "https://rpc.lavenderfive.com:443/noble"
provider = "LavenderFive"

# REST endpoints
[[chain.rest]]
url = "https://noble-api.polkachu.com"
provider = "Polkachu"

[[chain.rest]]
url = "https://noble-rest.owallet.io"
provider = "Owallet"

[[chain.rest]]
url = "https://rest.lavenderfive.com:443/noble"
provider = "LavenderFive"

[[token]]
denom = "ueure"
name = "Eure"
symbol = "EURe"
exponent = 6
icon = "https://raw.githubusercontent.com/Cogwheel-Validator/spectra-ibc-hub/main/images/noble/eure.png"
coingecko_id = "monerium-eur-money"
allowed_destinations = ["osmosis-1"]

[[token]]
denom = "uusdc"
name = "USDC"
symbol = "USDC"
exponent = 6
icon = "https://raw.githubusercontent.com/Cogwheel-Validator/spectra-ibc-hub/main/images/noble/usdc.png"
coingecko_id = "usd-coin"
allowed_destinations = ["cosmoshub-4", "stargaze-1", "osmosis-1"]

[[token]]
denom = "uusdn"
name = "USDN"
symbol = "USDN"
exponent = 6
icon = "https://raw.githubusercontent.com/Cogwheel-Validator/spectra-ibc-hub/main/images/noble/usdn.png"
coingecko_id = "neutrino-dollar"
allowed_destinations = ["osmosis-1"]

[[token]]
denom = "ausdy"
name = "USDY"
symbol = "USDY"
exponent = 18
icon = "https://raw.githubusercontent.com/Cogwheel-Validator/spectra-ibc-hub/main/images/noble/usdy.png"
coingecko_id = "ondo-us-dollar-yield"
allowed_destinations = ["osmosis-1"]