
[chain]
name = "Stargaze"
id = "stargaze-1"
type = "cosmos"
registry = "stargaze"
explorer_url = "https://mintscan.io/stargaze"
slip44 = 118
bech32_prefix = "stars"

is_broker = false
broker_id = ""

keplr_json = "stargaze.json"

# RPC endpoints
[[chain.rpcs]]
url = "https://stargaze-rpc.polkachu.com"
provider = "Polkachu"

[[chain.rpcs]]
url = "https://stargaze.ibs.team:443/rpc"
provider = "IBS Team"

[[chain.rpcs]]
url = "https://stargaze-rpc.stakerhouse.com"
provider = "Stakerhouse"

# REST endpoints
[[chain.rest]]
url = "https://stargaze-api.polkachu.com"
provider = "Polkachu"

[[chain.rest]]
url = "https://stargaze.ibs.team:443/api"
provider = "IBS Team"

[[chain.rest]]
url = "https://stargaze-rest.stakerhouse.com"
provider = "Stakerhouse"

[[token]]
denom = "ustars"
name = "Stargaze"
symbol = "STARS"
exponent = 6
icon = "https://raw.githubusercontent.com/Cogwheel-Validator/spectra-ibc-hub/main/images/stargaze/stars.png"
coingecko_id = "stargaze"
allowed_destinations = ["osmosis-1"]